# Generated by Django 4.2.3 on 2023-07-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoffeeShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("alamat", models.CharField(max_length=200)),
                ("jam_buka", models.CharField(max_length=100)),
                ("gallery", models.ImageField(upload_to="coffee_shop_gallery/")),
                ("contact", models.CharField(max_length=20)),
                ("review", models.TextField()),
            ],
        ),
    ]
