# Generated by Django 4.2.3 on 2023-07-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeshop", name="alamat", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="contact",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="gallery",
            field=models.ImageField(upload_to="coffeeshop_gallery/"),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="nama",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_menu", models.CharField(max_length=200)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "jenis_menu",
                    models.CharField(
                        choices=[("Coffee", "Coffee"), ("Non Coffee", "Non Coffee")],
                        max_length=20,
                    ),
                ),
                (
                    "coffee_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplikasi_tengo.coffeeshop",
                    ),
                ),
            ],
        ),
    ]
