# Generated by Django 4.2.3 on 2023-07-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aplikasi_tengo",
            "0002_alter_coffeeshop_alamat_alter_coffeeshop_contact_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="menu", name="coffee_shop",),
        migrations.RemoveField(model_name="menu", name="harga",),
        migrations.RemoveField(model_name="menu", name="jenis_menu",),
        migrations.RemoveField(model_name="menu", name="nama_menu",),
        migrations.AddField(
            model_name="menu",
            name="jenis",
            field=models.CharField(
                choices=[("coffee", "Coffee"), ("non_coffee", "Non Coffee")],
                default="coffee",
                max_length=10,
            ),
        ),
    ]
