# Generated by Django 4.2.3 on 2023-07-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0004_delete_menu_alter_coffeeshop_alamat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="video_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="coffeeshop", name="alamat", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="contact",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="gallery",
            field=models.ImageField(upload_to="coffeeshop_gallery"),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="jam_buka",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="nama",
            field=models.CharField(max_length=200),
        ),
    ]
