# Generated by Django 4.2.3 on 2023-07-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0006_remove_coffeeshop_video_url_coffeeshop_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="video_source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
