# Generated by Django 4.2.3 on 2023-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0007_coffeeshop_video_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="instagram",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
