# Generated by Django 4.2.3 on 2023-07-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0008_coffeeshop_instagram"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffeeshop", name="instagram",),
        migrations.AddField(
            model_name="coffeeshop",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
