# Generated by Django 4.2.3 on 2023-07-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0009_remove_coffeeshop_instagram_coffeeshop_instagram_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("deskripsi", models.TextField()),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "jenis",
                    models.CharField(
                        choices=[("makanan", "Makanan"), ("minuman", "Minuman")],
                        max_length=10,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="menu_photos/"),
                ),
                (
                    "coffee_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aplikasi_tengo.coffeeshop",
                    ),
                ),
            ],
        ),
    ]
