# Generated by Django 4.2.3 on 2023-07-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0010_menu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu", old_name="deskripsi", new_name="keterangan",
        ),
        migrations.RemoveField(model_name="menu", name="foto",),
        migrations.AlterField(
            model_name="menu",
            name="jenis",
            field=models.CharField(
                choices=[("Makanan", "Makanan"), ("Minuman", "Minuman")],
                default="Makanan",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="menu", name="nama", field=models.CharField(max_length=255),
        ),
    ]
