# Generated by Django 4.2.3 on 2023-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aplikasi_tengo",
            "0011_rename_deskripsi_menu_keterangan_remove_menu_foto_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu", old_name="keterangan", new_name="deskripsi",
        ),
        migrations.RemoveField(model_name="menu", name="jenis",),
        migrations.AlterField(
            model_name="menu",
            name="harga",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="menu", name="nama", field=models.CharField(max_length=100),
        ),
    ]
