# Generated by Django 4.2.3 on 2023-07-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aplikasi_tengo",
            "0012_rename_keterangan_menu_deskripsi_remove_menu_jenis_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="jenis_menu",
            field=models.CharField(
                choices=[("makanan", "Makanan"), ("minuman", "Minuman")],
                default="minuman",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="harga",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="menu", name="nama", field=models.CharField(max_length=255),
        ),
    ]
