# Generated by Django 4.2.3 on 2023-07-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0013_menu_jenis_menu_alter_menu_harga_alter_menu_nama"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="google_maps_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="Menu",),
    ]
