# Generated by Django 4.2.3 on 2023-08-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0017_coffeeshopimage"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffeeshop", name="video",),
        migrations.RemoveField(model_name="coffeeshop", name="video_source",),
    ]
