# Generated by Django 4.2.3 on 2023-09-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0018_remove_coffeeshop_video_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GambarLowongan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gambar", models.ImageField(upload_to="lowongan_gambar")),
            ],
        ),
    ]
