# Generated by Django 4.2.3 on 2023-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0019_gambarlowongan"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="tiktok_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
