# Generated by Django 4.2.3 on 2023-09-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0020_coffeeshop_tiktok_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoffeeShopTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50)),
            ],
        ),
    ]
