# Generated by Django 4.2.3 on 2023-09-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0021_coffeeshoptag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeshoptag",
            name="tag_name",
            field=models.CharField(
                choices=[
                    ("Ngopi", "Ngopi"),
                    ("Nugas", "Nugas"),
                    ("Nongkrong", "Nongkrong"),
                    ("Skripsian", "Skripsian"),
                    ("WFA", "WFA"),
                    ("Ngobrol", "Ngobrol"),
                    ("Nge-game", "Nge-game"),
                    ("Sekalian Makan", "Sekalian Makan"),
                ],
                max_length=50,
            ),
        ),
    ]
