# Generated by Django 4.2.3 on 2023-09-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0022_alter_coffeeshoptag_tag_name"),
    ]

    operations = [
        migrations.DeleteModel(name="CoffeeShopTag",),
        migrations.AddField(
            model_name="coffeeshop",
            name="tag_name",
            field=models.CharField(
                choices=[
                    ("Ngopi", "Ngopi"),
                    ("Nugas", "Nugas"),
                    ("Nongkrong", "Nongkrong"),
                    ("Skripsian", "Skripsian"),
                    ("WFA", "WFA"),
                    ("Ngobrol", "Ngobrol"),
                    ("Nge-game", "Nge-game"),
                    ("Sekalian Makan", "Sekalian Makan"),
                ],
                default="ngopi",
                max_length=50,
            ),
        ),
    ]
