# Generated by Django 4.2.3 on 2023-09-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0023_delete_coffeeshoptag_coffeeshop_tag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoffeeShopTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(model_name="coffeeshop", name="tag_name",),
        migrations.AddField(
            model_name="coffeeshop",
            name="tags",
            field=models.ManyToManyField(blank=True, to="aplikasi_tengo.coffeeshoptag"),
        ),
    ]
