# Generated by Django 4.2.3 on 2023-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0024_coffeeshoptag_remove_coffeeshop_tag_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
