# Generated by Django 4.2.3 on 2023-09-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0025_coffeeshop_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeshop",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
