# Generated by Django 4.2.3 on 2023-09-10 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0026_alter_coffeeshop_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
