# Generated by Django 4.2.3 on 2023-09-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0027_coffeeshop_created_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffeeshop", name="created_at",),
        migrations.AlterField(
            model_name="coffeeshop",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
