# Generated by Django 4.2.3 on 2023-09-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0028_remove_coffeeshop_created_at_alter_coffeeshop_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffeeshop", name="slug",),
    ]
