# Generated by Django 4.2.3 on 2023-09-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0031_subscription"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="user",),
    ]
