# Generated by Django 4.2.7 on 2023-11-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0032_remove_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
