# Generated by Django 5.0 on 2023-12-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0033_coffeeshop_updated_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffeeshop", name="updated_at",),
        migrations.AddField(
            model_name="coffeeshop",
            name="menu",
            field=models.URLField(blank=True, null=True),
        ),
    ]
