# Generated by Django 4.2.3 on 2023-12-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0034_remove_coffeeshop_updated_at_coffeeshop_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lokasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_lokasi", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="lokasi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
