# Generated by Django 4.2.3 on 2023-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0035_lokasi_coffeeshop_lokasi"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffeeshop", name="lokasi",),
        migrations.AddField(
            model_name="coffeeshop",
            name="lokasi",
            field=models.ManyToManyField(to="aplikasi_tengo.lokasi"),
        ),
    ]
