# Generated by Django 4.2.3 on 2024-02-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0036_remove_coffeeshop_lokasi_coffeeshop_lokasi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fasilitas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_fasilitas", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="fasilitas",
            field=models.ManyToManyField(blank=True, to="aplikasi_tengo.fasilitas"),
        ),
    ]
