# Generated by Django 4.2.3 on 2024-02-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0037_fasilitas_coffeeshop_fasilitas"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffeeshop", name="fasilitas",),
        migrations.DeleteModel(name="Fasilitas",),
        migrations.AddField(
            model_name="coffeeshop",
            name="fasilitas",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Musholla", "Musholla"),
                    ("AC", "AC"),
                    ("VIP Room", "VIP Room"),
                    ("Permainan", "Permainan"),
                ],
                help_text="Pilih fasilitas yang tersedia di tempat ngopi ini. (Boleh kosong jika tidak ada fasilitas)",
                max_length=20,
                null=True,
            ),
        ),
    ]
