# Generated by Django 4.2.3 on 2024-02-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aplikasi_tengo",
            "0038_remove_coffeeshop_fasilitas_delete_fasilitas_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Fasilitas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_fasilitas",
                    models.CharField(
                        choices=[
                            ("Musholla", "Musholla"),
                            ("AC", "AC"),
                            ("VIP Room", "VIP Room"),
                            ("Permainan", "Permainan"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="coffeeshop", name="fasilitas",),
        migrations.AddField(
            model_name="coffeeshop",
            name="fasilitas",
            field=models.ManyToManyField(blank=True, to="aplikasi_tengo.fasilitas"),
        ),
    ]
