# Generated by Django 4.2.3 on 2024-02-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0039_fasilitas_remove_coffeeshop_fasilitas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_url", models.URLField()),
                ("description", models.TextField()),
            ],
        ),
    ]
