# Generated by Django 4.2.3 on 2024-02-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aplikasi_tengo", "0040_recommendation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendation",
            old_name="description",
            new_name="twitter_embed",
        ),
        migrations.RemoveField(model_name="recommendation", name="tweet_url",),
    ]
