# Generated by Django 4.2.3 on 2024-02-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "aplikasi_tengo",
            "0041_rename_description_recommendation_twitter_embed_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(name="Recommendation",),
    ]
