# Generated by Django 5.1.1 on 2024-09-13 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0046_coffeeshop_latitude_coffeeshop_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('visit_later', 'Ingin Dikunjungi'), ('visited', 'Sudah Dikunjungi')], default='visit_later', max_length=20)),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikasi_tengo.coffeeshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'coffee_shop')},
            },
        ),
    ]
