# Generated by Django 5.1.1 on 2024-09-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0047_visitstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='menu',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='aplikasi_tengo.coffeeshop')),
            ],
        ),
    ]
