# Generated by Django 5.1.1 on 2024-09-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0048_remove_coffeeshop_menu_coffeeshop_menu_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='menu_image',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='menu_images',
            field=models.ManyToManyField(blank=True, related_name='coffee_shops', to='aplikasi_tengo.menuimage'),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images_related', to='aplikasi_tengo.coffeeshop'),
        ),
    ]
