# Generated by Django 5.1.1 on 2024-09-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0051_usertengo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTengo',
        ),
    ]
