# Generated by Django 5.1.1 on 2024-10-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0053_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='coffee_shop',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
