# Generated by Django 5.1.1 on 2024-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0054_remove_rating_coffee_shop_remove_rating_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='tahun_berdiri',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
