# Generated by Django 5.1.1 on 2024-10-19 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0055_coffeeshop_tahun_berdiri'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
