# Generated by Django 5.1.1 on 2025-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0056_coffeeshop_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuimage',
            name='image',
        ),
        migrations.AddField(
            model_name='menuimage',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='gallery',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
