# Generated by Django 5.1.1 on 2025-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0057_remove_menuimage_image_menuimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='gallery',
            field=models.ImageField(null=True, upload_to='coffeeshop_gallery'),
        ),
    ]
