# Generated by Django 5.1.1 on 2025-01-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_tengo', '0058_alter_coffeeshop_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='menu_images',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='menu_link',
            field=models.URLField(blank=True, verbose_name='MenuLink'),
        ),
    ]
